### PR TITLE
added navlinks

### LINKED ISSUE #2: 2. As a user, I want to be able to navigate to all the pages in the application by clicking the links in the nav bar
## Summary

Users need to be able to navigate between the pages of our application in order to access all of its features. There is a navigation bar in the `Layout.jsx` component, but it's not quite feature-complete: the links in the nav element don't actually allow the user to navigate from page to page.

## Acceptance criteria
- [x] The `nav` element is added to the `Layout` component
- [x] Links to the "Home", "List", and "Add item" pages of the app are In the `nav` element
- [x] The links all function as expected using  the `NavLink` component from `react-router-dom`

## Notes
- The [official docs for the `NavLink` component](https://reactrouterdotcom.fly.dev/docs/en/v6/components/nav-link) will come in very handy!
- While a standard anchor element (`<a>`) _could_ allow a user to navigate from page to page, the `NavLink` component adds additional behavior that is essential to our app functioning correctly!

### PR DESCRIPTION
**Pull request by kaitlinLewis**
## Description

This code allows the links in the nav bar to direct a user to the correct page. While a standard anchor element `<a>` could allow a user to navigate from page to page, the `<NavLink>` component adds additional behavior, such as keeping track of whether the link is active, thereby adding default styling, which will help with accessibility and breadcrumbs.

## Related Issue

Closes #2

## Acceptance Criteria

 The nav element is added to the Layout component
 Links to the "Home", "List", and "Add item" pages of the app are In the nav element
 The links all function as expected using the NavLink component from react-router-dom

## Type of Changes

|     | Type                       |
| --- | -------------------------- |
|   ✓    | :bug: Bug fix              |
|  | :sparkles: New feature     |
|     | :hammer: Refactoring       |
|     | :100: Add tests            |
|     | :link: Update dependencies |
|     | :scroll: Docs              |

## Testing Steps / QA Criteria

Test that Nav links are redirecting to correct view

### CODE REVIEW

**Comment by NuriyaAkh** [comment]
Awesome! Nav links work as expected

**Review by NuriyaAkh — APPROVED** [review]

**Comment by meera-ramesh19** [comment]
Looks great

**Review by meera-ramesh19 — APPROVED** [review]
Looks great

**Review by daredtech — APPROVED** [review]
Good job on your first pull request!

**Review by georgeoffley — APPROVED** [review]
Looks good!! Nice work!!!!

**Review by cafloyd — APPROVED** [review]

**Pull request merged**
